name: Deploy Astro to GitHub Pages

# Trigger this workflow when you push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the job on a GitHub-hosted Ubuntu machine
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use Node.js version 18
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Astro project
      - name: Build project
        run: npm run build

      # Step 5: Disable Jekyll
      - name: Disable Jekyll
        run: |
          touch dist/.nojekyll
          echo "Disabled Jekyll processing"

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false
          cname: ${{ secrets.CNAME }}  # Optional: If you have a custom domain
          force_orphan: true  # This will only keep the latest commit in the gh-pages branch
